import type { Metadata } from "next";
import "./globals.css";
import { Inter, Roboto_Mono, Bebas_Neue} from 'next/font/google'



export const metadata: Metadata = {
  title: "Crud",
  description: "Generated by Arthur",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`bg-gray-900 text-white h-full w-full`}
      >
        {children}
      </body>
    </html>
  );
}
